server:
  port: 8801
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeeee_manage?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 600000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      static-locations: classpath:/static/

# 本地上传文件保存路径
local:
  upload:
    location: C:\
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
# 授权配置
user:
  auth:
    uri: http://127.0.0.1:${server.port}/oauth/token
    client-Id: yeeee_crowdfunding-web
    client-secret: 111111
    grant-type: password
secure:
  ignore:
    urls:
      - "/"
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.jpg"
      - "/**/*.ico"
      - "/**/*.html"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/auth/oauth/**"
      - "/auth/rsa/publicKey"
      - "/front/user/login"
      - "/front/user/register"
      - "/admin/sys-user/login"
      - "/user/webSocket/**"

# swagger文档增强功能
knife4j:
  enable: true
